<a href="https://colab.research.google.com/github/ayushi-get/breast/blob/main/Breast_cancer_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
from sklearn.datasets import load_breast_cancer 

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
from keras.models import Sequential

In [7]:
from keras.layers import Dense

In [8]:
data =load_breast_cancer()

In [9]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.

In [13]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [12]:

print(data['DESCR'])


.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [11]:
data['data'].shape

(569, 30)

In [15]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [16]:
data['data'][0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [18]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [20]:
j=0
for i in data['feature_names']:
  print(i,":",data['data'][0][j])
  j+=1


mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


In [22]:
feature = data['data']

label = data['target']

data['target_names']

feature.shape

label.shape

scale = StandardScaler()

feature = scale.fit_transform(feature)

j = 0
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

print(feature[568])


mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
worst conca

In [23]:
print(data['target_names'][label[568]],label[568])

df_frt = pd.DataFrame(feature , columns = data['feature_names'])
df_lbl = pd.DataFrame(label , columns = ['label'])
df = pd.concat([df_frt, df_lbl], axis=1)
df = df.sample(frac = 1)

feature = df.values[ : , : 30]
label = df.values[ : ,30: ]

df


benign 1


mean radius  mean texture  ...  worst fractal dimension  label
310    -0.689385     -0.041805  ...                -0.796094      1
558     0.131416      0.788958  ...                -0.216444      1
33      1.460602      1.670916  ...                 1.571270      0
102    -0.553058      0.286311  ...                -0.840426      1
342    -0.871154     -1.007538  ...                 0.379830      1
..           ...           ...  ...                      ...    ...
532    -0.127037     -0.688730  ...                -0.339467      1
316    -0.553058     -1.212320  ...                -1.306473      1
191    -0.385490      0.493420  ...                -0.844305      1
527    -0.507616     -1.633519  ...                -0.444757      1
44     -0.271884      0.586503  ...                 0.677967      0

[569 rows x 31 columns]

In [24]:
X_train = feature[:500]
y_train = label[:500]


In [25]:
X_train

array([[-0.68938531, -0.04180541, -0.72655532, ..., -0.87090386,
         0.94841464, -0.7960935 ],
       [ 0.13141571,  0.78895755,  0.1821005 , ..., -0.06252381,
        -1.03983773, -0.21644405],
       [ 1.46060215,  1.67091599,  1.48000371, ...,  0.97288481,
         1.24770406,  1.57127022],
       ...,
       [-0.70074588, -0.51652711, -0.75250514, ..., -1.09610524,
        -0.2746275 , -0.86979654],
       [-0.0929555 , -0.8143917 , -0.06339309, ...,  0.3607756 ,
        -0.50435235,  1.05590311],
       [ 1.32995562,  0.16064943,  1.19167231, ...,  0.22525888,
        -0.53994352, -1.47272064]])

In [26]:
X_val = feature[500:535]
y_val = label[500:535]

#34 Testing
X_test = feature[535:]
y_test = label[535:]


In [27]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

Lr=LogisticRegression(random_state=0)
Lr.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(random_state=0)

In [30]:
predict=Lr.predict(X_val)

In [31]:
from sklearn.metrics import accuracy_score

print(accuracy_score(predict,y_val))

1.0


In [32]:
predict=Lr.predict(X_test)


In [33]:
print(accuracy_score(predict,y_test))

0.9705882352941176


In [41]:
# svm
from sklearn import svm
regressor = svm.SVC()
regressor.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [42]:
predict=regressor.predict(X_val)


In [43]:
predict

array([1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       0.])

In [44]:
print(accuracy_score(predict,y_val))

1.0


In [40]:
predict

array([ 1.04217414, -0.20666476,  0.29661567,  0.92433918,  1.12920858,
        1.11454415,  0.46286118, -0.03827579,  1.07891034,  0.99571064,
        0.60583945,  1.06017377, -0.25176811,  0.0601107 ,  0.96047855,
        0.51975482,  0.90721586,  1.10840092,  0.09348894,  1.00697103,
       -0.14795772,  1.14229021,  0.95824601,  1.09489483,  0.01540676,
        1.01879635,  0.02869993,  1.13029566,  0.04581527,  0.86750044,
        0.60407067,  1.10886266,  1.0353682 ,  1.01295505, -0.13243628])

In [45]:
predict=regressor.predict(X_test)

In [46]:
print(accuracy_score(predict,y_test))

0.9705882352941176


In [49]:
# decision tree classifer
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  

In [51]:
classifier.fit(X_train, y_train)  

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [52]:
predict=classifier.predict(X_val)


In [53]:
print(accuracy_score(predict,y_val))

0.9142857142857143


In [54]:
predict=classifier.predict(X_test)

In [55]:
print(accuracy_score(predict,y_test))

0.9411764705882353


In [47]:
# Random forest classifier


In [60]:
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy") 

In [62]:
classifier.fit(X_train, y_train)  

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(criterion='entropy', n_estimators=10)

In [63]:
predict=classifier.predict(X_val)

In [64]:
print(accuracy_score(predict,y_val))

0.9428571428571428


In [65]:
predict=classifier.predict(X_test)

In [66]:
print(accuracy_score(predict,y_test))

0.9411764705882353


In [68]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=10)
neigh.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=10)

In [69]:
predict=neigh.predict(X_val)

In [70]:
print(accuracy_score(predict,y_val))

0.9428571428571428


In [71]:
predict=neigh.predict(X_test)

In [72]:
print(accuracy_score(predict,y_test))

0.9705882352941176
